### PR TITLE
Replace iPhone Dev Wiki with The Apple Wiki

### PR DESCRIPTION
**Pull request by iAdam1n**
Replacing iPhone Dev Wiki links with The Apple Wiki since Dev Wiki is legacy and hardly updated anymore (all content has been added to The Apple Wiki).

### CODE REVIEW

**Comment by L1ghtmann** [comment]
Hey, thanks! I don't really have a preference either way re the hyperlinks, especially if the apple wiki has additional content that the dev wiki does not, but part of me thinks it may be worth keeping the dev wiki sidebar link. If I had to guess, it'd wager that it's still the go-to for most people (myself included). Curious how others feel though.

**Comment by NightwindDev** [comment]
As requested by @leptos-null, I am leaving my opinion on this PR here.

Both developer wikis are/were very useful in finding information about Darwin development. Since the iPhone Dev Wiki appears to be offline at the moment, I personally would be interested in seeing the links leading to the iPhone Dev Wiki with The Apple Wiki. The information presented on The Apple Wiki appears to be more up-to-date as well.

**Review by leptos-null — APPROVED** [review]
All links look good.
Thanks for these changes.

@iAdam1n may you merge/ rebase with the base branch to resolve conflicts?

**Comment by leptos-null** [comment]
Thanks Nightwind. Sounds good to me.

**Comment by iAdam1n** [comment]
> All links look good. Thanks for these changes.
> 
> @iAdam1n may you merge/ rebase with the base branch to resolve conflicts?

I think that did it? Never done that before so please let me know.

**Review by leptos-null — APPROVED** [review]
Yep, looks great, thanks!

**Review by L1ghtmann — APPROVED** [review]
Thanks again

**Pull request merged**
